// Offline deal-pool generator. Runs in Node only (never loaded by the browser).
//   node tools/generate-deals.mjs   (or: npm run gen)
//
// Generates many deterministic shuffles, scores each with the difficulty
// heuristic, then samples evenly across fixed percentile bands into four
// buckets and writes src/deals.js. Output is fully deterministic (seeded RNG,
// no timestamps) so CI can verify it is up to date with `git diff --exit-code`.

import engine from '../src/engine.js';
import heuristic from '../src/heuristic.js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const N = 20000;          // candidate deals to score
const PER_BUCKET = 150;   // deals kept per difficulty

// Percentile bands within the sorted-by-difficulty list (low score = easy).
const BANDS = {
  easy:   [0.00, 0.18],
  hard:   [0.34, 0.54],
  expert: [0.62, 0.82],
  master: [0.90, 1.00]
};

function generate() {
  const scored = [];
  for (let seed = 1; seed <= N; seed++) {
    const order = engine.shuffledOrder(seed);
    scored.push({ order, score: heuristic.scoreDeal(order) });
  }
  scored.sort((a, b) => a.score - b.score);

  const buckets = {};
  const ranges = {};
  for (const [name, band] of Object.entries(BANDS)) {
    const start = Math.floor(band[0] * (scored.length - 1));
    const end = Math.floor(band[1] * (scored.length - 1));
    const span = end - start;
    const out = [];
    for (let k = 0; k < PER_BUCKET; k++) {
      const idx = start + Math.round((span * k) / (PER_BUCKET - 1));
      out.push(scored[idx].order);
    }
    buckets[name] = out;
    ranges[name] = [scored[start].score, scored[end].score];
  }
  return { buckets, ranges };
}

function serialize({ buckets, ranges }) {
  let s = '';
  s += '// AUTO-GENERATED by tools/generate-deals.mjs — do not edit by hand.\n';
  s += '// Regenerate with: npm run gen\n';
  s += `// Params: N=${N}, perBucket=${PER_BUCKET}, weights=${JSON.stringify(heuristic.WEIGHTS)}\n`;
  s += `// Difficulty score ranges: ${JSON.stringify(ranges)}\n`;
  s += 'window.Solitaire = window.Solitaire || {};\n';
  s += 'window.Solitaire.DEALS = {\n';
  const names = Object.keys(buckets);
  names.forEach((name, ni) => {
    s += `  "${name}": [\n`;
    s += buckets[name].map((o) => '    ' + JSON.stringify(o)).join(',\n');
    s += '\n  ]' + (ni < names.length - 1 ? ',' : '') + '\n';
  });
  s += '};\n';
  return s;
}

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'src', 'deals.js');
const result = generate();
writeFileSync(outPath, serialize(result));
console.log('Wrote src/deals.js');
console.log('Difficulty score ranges:', result.ranges);
for (const k of Object.keys(result.buckets)) {
  console.log(`  ${k}: ${result.buckets[k].length} deals`);
}
