// Offline deal-pool generator. Runs in Node only (never loaded by the browser).
//   node tools/generate-deals.mjs   (or: npm run gen)
//
// Issue #1: every bundled deal is now VERIFIED WINNABLE by the offline solver
// (tools/solver.mjs) before it is written. We scan deterministic seeded
// shuffles, run the solver on each, and keep only deals it can actually win.
//
// Difficulty is the solver's SEARCH EFFORT (nodes expanded to find a win):
// trivial deals fall in a few hundred nodes, tangled ones take tens of
// thousands. We collect a pool of solvable deals, sort by effort, and split it
// into four equal quartiles — easy / hard / expert / master. Unlike the old
// heuristic buckets, "master" now means "winnable but hard to untangle", not
// "statistically brutal, maybe impossible" (see SCOPE.md §4).
//
// Output is fully deterministic (seeded RNG, fixed solver, no timestamps) so CI
// can verify src/deals.js is up to date with `git diff --exit-code`.

import engine from '../src/engine.js';
import solver from './solver.mjs';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const PER_BUCKET = 100;             // deals kept per difficulty
const MAX_NODES = 150000;           // solver budget per deal (cap-hit = discarded)
const MAX_SCAN = 5000;              // safety cap on seeds scanned
const NEEDED = PER_BUCKET * 4;      // total solvable deals required
const BUCKETS = ['easy', 'hard', 'expert', 'master'];

function collectSolvable() {
  const solved = [];
  let seed = 0;
  while (solved.length < NEEDED && seed < MAX_SCAN) {
    seed++;
    const order = engine.shuffledOrder(seed);
    const r = solver.solve(order, { maxNodes: MAX_NODES });
    if (r.solved) solved.push({ order, nodes: r.nodes });
    if (seed % 200 === 0) {
      console.log(`  scanned ${seed} seeds, ${solved.length}/${NEEDED} solvable kept`);
    }
  }
  if (solved.length < NEEDED) {
    throw new Error(`only found ${solved.length}/${NEEDED} solvable deals within ${MAX_SCAN} seeds`);
  }
  return { solved, scanned: seed };
}

function bucketize(solved) {
  // Sort by ascending search effort, then split into four equal contiguous
  // quartiles. Ties broken by order string so the result is deterministic.
  solved.sort((a, b) => (a.nodes - b.nodes) || (a.order.join() < b.order.join() ? -1 : 1));
  const buckets = {};
  const ranges = {};
  BUCKETS.forEach((name, b) => {
    const slice = solved.slice(b * PER_BUCKET, (b + 1) * PER_BUCKET);
    buckets[name] = slice.map((d) => d.order);
    ranges[name] = [slice[0].nodes, slice[slice.length - 1].nodes];
  });
  return { buckets, ranges };
}

function serialize({ buckets, ranges }, scanned) {
  let s = '';
  s += '// AUTO-GENERATED by tools/generate-deals.mjs — do not edit by hand.\n';
  s += '// Regenerate with: npm run gen\n';
  s += `// Every deal below is SOLVER-VERIFIED WINNABLE (tools/solver.mjs, maxNodes=${MAX_NODES}).\n`;
  s += `// Params: perBucket=${PER_BUCKET}, scanned ${scanned} seeded shuffles.\n`;
  s += `// Difficulty = solver search effort (nodes). Per-bucket node ranges: ${JSON.stringify(ranges)}\n`;
  s += 'window.Solitaire = window.Solitaire || {};\n';
  s += 'window.Solitaire.DEALS = {\n';
  const names = Object.keys(buckets);
  names.forEach((name, ni) => {
    s += `  "${name}": [\n`;
    s += buckets[name].map((o) => '    ' + JSON.stringify(o)).join(',\n');
    s += '\n  ]' + (ni < names.length - 1 ? ',' : '') + '\n';
  });
  s += '};\n';
  return s;
}

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'src', 'deals.js');

console.log(`Scanning seeded shuffles for ${NEEDED} solver-verified-winnable deals...`);
const { solved, scanned } = collectSolvable();
const result = bucketize(solved);
writeFileSync(outPath, serialize(result, scanned));
console.log(`Wrote src/deals.js (${scanned} seeds scanned, ${solved.length} solvable kept)`);
console.log('Per-bucket solver-effort (node) ranges:', result.ranges);
for (const k of BUCKETS) console.log(`  ${k}: ${result.buckets[k].length} deals`);
