// AUTO-GENERATED by tools/generate-deals.mjs — do not edit by hand.
// Regenerate with: npm run gen
// Every deal below is SOLVER-VERIFIED WINNABLE (src/solver.js, maxNodes=150000).
// Difficulty = win rate of an imperfect simulated player; higher level = lower win rate.
//   easy/hard split on a CASUAL player (80 trials, mistake=0.18).
//   expert/master split on a SKILLED player (120 trials, mistake=0.04).
// Win-rate ranges (casual for easy/hard, skilled for expert/master): easy [94%,100%], hard [19%,76%], expert [9%,28%], master [0%,3%]
// Params: perBucket=8, scanned 111 seeds (63 winnable).
window.Solitaire = window.Solitaire || {};
window.Solitaire.DEALS = {
  "easy": [
    ["AH","KS","TC","7D","8H","3C","JH","9D","KC","6D","QS","7S","KH","3H","QD","6C","7C","3S","2C","TH","9S","8S","AC","AS","9C","AD","QH","8C","TD","JC","2D","6H","5H","KD","5D","2S","6S","8D","9H","4S","3D","7H","4H","2H","5S","4C","JD","JS","5C","QC","4D","TS"],
    ["6D","KS","TH","TD","9D","9C","KD","JH","5C","AS","TS","3C","4D","3D","2S","5D","4S","6C","JS","QH","AH","7S","JD","5H","3S","JC","QS","7C","KC","QC","9H","TC","9S","8H","2H","7D","5S","6S","8D","AD","KH","2C","6H","QD","3H","7H","AC","8C","8S","4H","4C","2D"],
    ["KC","5D","2D","TC","AS","6C","3S","9C","TD","6S","KD","QS","4D","JD","AH","8H","7H","JS","2S","5S","7D","KH","9S","8S","8C","3H","KS","5H","TS","JC","TH","JH","9H","7S","4S","8D","AD","9D","7C","QC","6H","2H","QH","QD","3D","5C","AC","2C","3C","4C","6D","4H"],
    ["QH","5D","5H","9S","3D","5S","AC","4D","2H","TS","6S","KC","QS","JS","2S","AD","2C","6H","3C","TD","JD","6C","7H","7S","JH","3H","QD","KD","AH","KS","8S","4C","TH","5C","4S","9H","8C","9C","9D","QC","7C","JC","3S","6D","KH","8H","TC","8D","2D","4H","7D","AS"],
    ["4S","2S","TS","JH","5S","7S","QC","KD","9C","TH","6D","7C","4C","6C","2C","QD","QS","TD","5D","5H","2D","7D","2H","JC","8S","4H","KS","3D","4D","9S","8C","6S","AS","3C","5C","8D","JD","7H","JS","TC","8H","AD","3S","9H","AH","KC","KH","9D","AC","6H","QH","3H"],
    ["3D","AD","6D","4H","QS","QC","7D","5D","2C","TH","4S","3H","7S","TD","4D","8D","3S","2H","9H","KD","8S","QH","QD","KS","AC","6C","JD","7C","9S","TC","5C","KH","6H","JC","5H","6S","7H","3C","JH","4C","2D","9D","9C","8H","5S","AH","2S","AS","8C","KC","TS","JS"],
    ["6D","JS","7S","2D","9D","2C","TD","7H","KH","6C","5D","TS","5S","QS","4H","3H","4C","8S","KS","TH","AS","3S","8H","8D","AC","JH","KC","5C","QC","7C","4D","9C","JC","2H","QD","TC","8C","3D","QH","9S","AD","9H","5H","3C","7D","4S","JD","2S","AH","6H","KD","6S"],
    ["JS","JD","5S","6S","AS","AD","6C","2D","4H","3S","7C","2S","TS","3C","7D","9D","QD","2H","4D","QS","5C","3D","QC","JH","KS","4S","5D","7S","TH","6D","5H","9S","9H","2C","TC","7H","KD","8C","QH","AH","9C","8D","6H","8H","AC","3H","KC","JC","KH","TD","8S","4C"]
  ],
  "hard": [
    ["QD","6S","JD","JC","5S","6H","QS","3S","7C","4H","TH","TD","2S","9H","QC","4C","JS","8H","9C","2D","5C","2H","7S","KH","5H","8C","9D","4D","KC","2C","JH","QH","KD","9S","3C","5D","AS","TC","3D","6C","8D","7D","4S","6D","KS","3H","AD","8S","TS","AH","AC","7H"],
    ["JS","6C","JD","8D","7D","AC","3S","JH","QS","2D","2H","TS","8H","KD","9S","6S","KH","4D","5H","7S","6D","4S","QC","8C","AH","TC","KC","7H","4H","AS","AD","5D","2C","5C","2S","QD","TH","7C","KS","5S","4C","8S","3C","TD","JC","QH","9D","3H","9H","3D","6H","9C"],
    ["TS","QD","9S","3D","5C","TH","AC","JS","7H","9C","QH","JC","8H","6S","4H","QS","3C","9D","6H","KH","2C","JH","2D","8C","4S","3S","TD","QC","AS","5D","7S","6D","KC","AD","TC","7C","6C","8S","5S","4D","9H","8D","7D","KS","JD","4C","KD","2S","3H","5H","2H","AH"],
    ["AH","JH","6C","3S","TH","TS","JD","7C","9H","TD","2H","8C","TC","5D","KD","4S","QD","6D","JS","5H","2S","6S","QH","4H","7S","7D","5C","8S","AS","2D","2C","QC","KH","7H","8H","4C","9S","9C","3H","AC","KS","3D","4D","3C","AD","5S","6H","JC","9D","QS","8D","KC"],
    ["6S","AD","TH","3H","3D","TD","TC","TS","AS","6H","2D","6D","8H","KD","JD","JH","5S","4H","2H","QH","3C","9S","7C","3S","JS","4D","2C","8S","QS","9H","4C","QD","9D","AH","KH","9C","7S","2S","7D","8C","6C","5C","AC","KS","5H","8D","4S","5D","JC","QC","KC","7H"],
    ["5H","5S","3H","KD","7S","5D","2C","4H","3C","4D","5C","2S","9H","KH","TD","QD","JD","JC","8S","KS","7D","9D","AH","TH","QC","7H","3D","QS","QH","2H","4C","8C","9S","9C","2D","6S","TS","AS","JS","AC","KC","3S","AD","TC","8H","8D","JH","7C","6D","6C","4S","6H"],
    ["JC","AD","TH","QC","AS","KH","7C","3D","6D","5S","4H","KC","JS","2H","7S","9H","3S","QH","3C","8C","8H","QS","TD","7D","AC","6S","JH","KS","6H","4D","2S","KD","9D","4S","TC","3H","5D","8D","9C","2D","4C","6C","9S","2C","TS","8S","5H","QD","AH","JD","5C","7H"],
    ["JH","KH","TC","8S","JS","3S","QS","AH","8D","5D","KD","2C","9C","AC","6H","3H","JC","4D","AS","6C","2D","AD","4S","5H","KS","6S","5C","QD","9S","2S","8H","6D","7S","8C","TH","4H","TS","3D","9D","JD","3C","QC","7H","9H","7D","7C","QH","TD","4C","KC","2H","5S"]
  ],
  "expert": [
    ["3D","TH","9S","QS","KC","3C","6C","5C","9D","5D","7C","8D","4S","KS","8H","AD","AH","KH","AS","2D","6S","2S","4H","JC","7D","2H","3S","9H","AC","6H","KD","4D","7S","TC","QD","5S","7H","5H","6D","3H","TS","9C","JD","QC","8C","8S","JS","JH","4C","TD","2C","QH"],
    ["7C","2D","6S","QH","5H","TD","JH","TH","4H","7D","5D","KD","2H","7H","8C","QD","6D","8D","3C","5C","JD","AC","QC","5S","8H","KS","7S","9C","AD","3S","QS","KC","2S","6H","3H","JC","JS","4D","TS","3D","6C","KH","4S","2C","4C","TC","9S","9D","AS","9H","8S","AH"],
    ["7H","5D","JS","9D","JD","JH","AC","AH","4H","JC","KC","QH","TC","9C","AS","KD","9H","QC","6C","5H","7C","5C","3H","6H","9S","8D","TS","3C","KH","4D","TH","6S","2C","2H","5S","8S","4S","4C","7S","QD","AD","8C","8H","7D","3D","2S","3S","QS","6D","2D","KS","TD"],
    ["KC","6C","7C","JC","5D","AC","KH","6D","TS","JD","TD","3S","6S","6H","JS","5H","3D","3C","9S","KS","QH","4S","AD","QC","4D","8S","8H","AS","7D","5C","2D","4C","QD","8D","8C","9H","2S","TH","4H","7S","7H","KD","9D","3H","5S","9C","2H","TC","JH","2C","QS","AH"],
    ["AH","9S","JH","TS","TC","KD","KH","QD","6C","3C","AS","QH","8D","QS","3H","2H","JC","4S","AC","7S","9H","2S","QC","TD","JS","6H","5S","5D","AD","7D","9D","6D","JD","7H","KC","2D","5H","7C","6S","9C","3D","4C","8S","5C","8C","4H","TH","4D","KS","2C","3S","8H"],
    ["KH","6C","3S","5C","8D","KC","7H","8C","JD","TH","3H","6H","4D","4C","6D","9D","5D","4H","3D","2H","AS","9H","7S","KS","JS","AC","AD","KD","JH","4S","QD","7C","9S","8H","2D","TD","AH","5H","2S","TS","TC","JC","5S","8S","9C","3C","QC","6S","7D","QH","QS","2C"],
    ["8H","KH","5H","6C","8D","QS","7C","4D","7S","AS","5C","KD","KC","8S","4C","AC","JS","9S","JC","7D","2H","2S","4S","QC","AD","6D","9D","3D","2D","AH","QD","9C","3H","3C","8C","TC","JD","TS","3S","TH","7H","QH","5D","KS","JH","5S","9H","2C","4H","6S","6H","TD"],
    ["QS","8S","TS","QH","TD","TC","AC","7S","KD","7H","KH","2D","AS","9H","3H","5C","3S","9C","JC","QD","5S","JS","4D","3D","AD","6S","8H","JH","2C","5D","3C","4S","2H","5H","7C","AH","KC","4C","6H","8D","QC","4H","9D","8C","7D","6D","TH","9S","JD","6C","2S","KS"]
  ],
  "master": [
    ["7C","3C","2S","6H","8D","9S","TS","6D","5D","QH","9D","AD","JS","AS","5S","TH","2H","7D","TC","5H","8C","JC","3H","JD","3D","QC","KD","AC","JH","4C","KS","8S","2C","3S","KC","QD","6C","7S","7H","6S","9C","8H","5C","9H","QS","TD","4H","4S","AH","2D","4D","KH"],
    ["4S","8S","2S","3C","3D","2D","QH","4H","TD","7S","7D","4D","JH","9H","AD","5S","6S","9S","9D","6H","3H","6D","2C","6C","QD","KC","4C","8C","7C","KS","KH","9C","JD","KD","JS","3S","QC","5D","AC","AH","TS","7H","TC","QS","8D","8H","2H","5C","5H","JC","AS","TH"],
    ["6S","JC","QH","KC","2C","7D","JS","KH","KD","8C","5S","2S","8D","9H","5H","7H","2D","8S","6C","TH","QC","5C","9D","QD","3H","6D","9S","JD","KS","9C","JH","6H","7C","AD","4D","TD","4H","5D","3C","7S","3D","AS","TS","4S","3S","QS","4C","AH","TC","8H","AC","2H"],
    ["JD","TC","QS","5D","7S","9C","AH","4D","2S","8H","9S","4H","AS","3C","KS","5S","3D","QC","JS","TD","JH","KC","KH","2C","8S","2D","4S","3H","5C","6C","2H","QH","7H","TH","6D","3S","AD","8C","8D","5H","7C","6S","6H","QD","JC","9D","7D","KD","9H","TS","4C","AC"],
    ["AC","3D","9C","AS","6H","TD","3C","5H","7D","3H","TS","7C","5D","8S","TH","JS","8D","4C","AD","4D","KD","QH","9S","5C","9D","2C","TC","8H","QS","AH","2D","KH","6S","6D","7S","JD","4S","KS","JH","QC","QD","4H","2H","6C","3S","KC","7H","9H","2S","8C","5S","JC"],
    ["2S","JS","AC","6H","TH","JC","3C","3D","KC","9S","2C","9D","QC","9H","AD","6S","5D","2D","5C","QS","AS","TD","5S","7D","3H","2H","7S","6C","8S","8C","QH","JH","3S","4H","QD","8H","4C","4S","6D","9C","KS","4D","JD","7C","TS","7H","KD","KH","TC","AH","5H","8D"],
    ["QC","QD","2D","5D","4D","2S","6S","5H","7H","AH","8D","5C","9D","TC","2H","3H","3D","AC","7S","KD","4H","3S","8S","5S","TS","KS","7C","JD","QH","9C","JC","6C","AS","8C","2C","6H","8H","KC","3C","TH","9H","KH","6D","4S","4C","7D","9S","AD","JS","QS","JH","TD"],
    ["AH","4D","6C","7H","6H","JS","2D","QD","3C","AS","4H","2H","2C","QH","KC","9S","4C","TH","QS","6D","AD","8H","5C","QC","TD","4S","TS","JC","KD","AC","JH","TC","7C","8S","5S","JD","KH","5H","3H","3S","5D","9H","3D","7S","7D","2S","8D","8C","9C","9D","KS","6S"]
  ]
};
